apiVersion: flightctl.io/v1alpha1
kind: CatalogItem
metadata:
  name: nginx-trustify-demo
  catalog: infrastructure
  labels:
    category: security
    demo: "true"
    runtime: docker
    os: debian

spec:
  type: container

  displayName: NGINX 1.20.1 (Trustify Demo)

  shortDescription: >
    Vulnerable NGINX 1.20.1 container image for
    SBOM generation and CVE detection demonstrations
    using Trustify.

  artifacts:
    - type: container
      uri: docker.io/library/nginx

  versions:
    - version: "1.20.1"
      references:
        container: "1.20.1"
      channels:
        - demo
