apiVersion: flightctl.io/v1alpha1
kind: CatalogItem
metadata:
  name: nginx-webserver02
  catalog: infrastructure
  labels:
    category: web
spec:
  type: container
  displayName: Nginx Web Server GitOps
  shortDescription: Lightweight high-performance web server GitOps
  artifacts:
    - type: container
      uri: docker.io/library/nginx
  versions:
    - version: "1.27.0"
      references:
        container: "1.27.0-alpine" # ここをマップ形式（キー: 値）にします
      channels:
        - stable
